Избирательное поведение
htmlacademy-yii/788313-task-force-1 pull request #12
Opened 2021-08-02 20:49 UTC by Vladlen67

2021-08-04 07:42 UTC, html-malex requested changes
Требуется доработка

2021-08-04 07:42 UTC, html-malex commented on yii-taskforce/frontend/controllers/UsersController.php
>          $this->sortUser = 'date_reg';
Сортировка должна задаваться параметром в запросе

2021-08-04 07:42 UTC, html-malex commented on yii-taskforce/frontend/controllers/TasksController.php
>              ->orderBy('date_create DESC')
Сортировка должна задаваться параметром в запросе

2021-08-04 07:42 UTC, html-malex commented on yii-taskforce/frontend/views/tasks/index.php
> +                        <div class="new-task__icon new-task__icon--<?php echo $task->category->code ?>"></div>
Не совсем понял, зачем это

2021-08-04 07:51 UTC, Vladlen67 commented on yii-taskforce/frontend/views/tasks/index.php
> +                        <div class="new-task__icon new-task__icon--<?php echo $task->category->code ?>"></div>
Это изменение класса, что бы менялась картинка в зависимости от категории, правда, там пришлось, слегка дописать CSS для них, а то некоторые неправильно отображались

2021-08-19 19:53 UTC, html-malex commented on yii-taskforce/frontend/models/Category.php
> + * @property Task[] $task
Массив заданий -> $tasks
Массив пользователей -> $users

2021-08-19 19:54 UTC, html-malex commented on yii-taskforce/frontend/models/TaskForm.php
> +    public function getPeriod()
Не указано возвращаемое значение

2021-08-19 19:55 UTC, merged