Add exception status and role
htmlacademy-yii/788313-task-force-1 pull request #6
Opened 2021-01-24 18:01 UTC by Vladlen67

2021-01-27 06:10 UTC, html-malex commented on src/Task.php
> +        try {
Непонятно, зачем делать try/catch блок, если после него все равно присваивается значение статуса, даже невалидное

2021-01-27 06:10 UTC, html-malex commented on src/Task.php
> +        try {
Непонятно, откуда "магические" идентификаторы клиентов 0 и 1
Почему проверяются именно они?

2021-01-27 06:17 UTC, html-malex requested changes
- убрать из индекса git файл `.phpunit.result.cache`
- оставить только один класс исключения
- выбросы (throw) исключений должны быть при нарушении ожидаемого хода программы

2021-02-01 09:29 UTC, Vladlen67 commented on src/Task.php
> +        try {
Это ожидаемый ход программы. Я не создавал отдельную таблицу, только для определения роли пользователя, когда это можно сделать программно. Получается во входящем параметре может быть только 0 - заказчик и 1 - исполнитель.

2021-02-02 16:15 UTC, html-malex approved these changes

2021-02-02 16:16 UTC, merged